import { Button, VerticalBox, HorizontalBox, ScrollView } from "std-widgets.slint";
import { Sidebar } from "sidebar.slint";

export component AppWindow inherits Window {
    width: 1200px;
    height: 700px;

    icon: @image-url("../assets/Alive-Wallpaper-Engine.png");
    title: "Alive wallpaper engine";

    background: #000000;

    callback import_wallpaper();

    VerticalBox {

        HorizontalBox {
            height: 700px; // dont remove this idc why than HorizontalBox just get half
            // when add Sidebar
            
            // left side sidebar
            Rectangle {

                width: 220px;

                Sidebar { // just for testing
                    import_wallpaper => { 
                        root.import_wallpaper();
                    }
                }

            }

            // right side one
            Rectangle {

                background: #111318;

                VerticalBox {

                    // live perview 
                    Rectangle {
                        height: 300px;
                        background: #044bff;
                    }

                    // wallpaper lib
                    Rectangle {
                        background: #0de057;
                    }
                }
            }
        }
    }
}