import { Button, VerticalBox, HorizontalBox, ScrollView } from "std-widgets.slint";
import { SidebarButton } from "sidebar-button.slint";

export component AppWindow inherits Window {
    width: 1200px;
    height: 700px;

    icon: @image-url("../assets/Alive-Wallpaper-Engine.png");
    title: "Alive wallpaper engine";

    background: #000000;

    callback import_wallpaper();

    VerticalBox {

        HorizontalBox {

            // left side sidebar
            Rectangle {
                width: 220px;
                background: #171a22;

                SidebarButton { // just for testing
                    title: "➕ Import Wallpaper";
                    clicked => { 
                        root.import_wallpaper();
                    }
                }

            }

            // right side one
            Rectangle {

                background: #111318;

                VerticalBox {

                    // live perview 
                    Rectangle {
                        height: 300px;
                        background: #044bff;
                    }

                    // wallpaper lib
                    Rectangle {
                        background: #0de057;
                    }
                }
            }
        }
    }
}