export component SidebarButton inherits Rectangle {
    
    height: 42px;
    background: #940cbe;
    border-radius: 8px;
    

    in property <string> title;
    callback clicked();

    Text {
        x : 10px;
        text: title;
        color: white;
        font-size: 15px;
        vertical-alignment: center;
    }

    ta := TouchArea {
        clicked => {
            root.clicked();
        }
        
    }
    
    states [
        hover when ta.has-hover: {
            background: #30384a;
        }
    ]

}