import { VerticalBox } from "std-widgets.slint";
import { SidebarButton } from "sidebar-button.slint";
import { Theme } from "../theme.slint";

export component AppSidebar inherits Rectangle {
    background: Theme.sidebar-background;
    width: Theme.sidebar-width;
    border-radius: Theme.radius-small;
    border-width: Theme.border-thin;
    border-color: Theme.sidebar-border;

    callback import_wallpaper();
    callback show_about();

    VerticalBox {
        padding: Theme.spacing-small;
        spacing: Theme.spacing-small;

        SidebarButton {
            title: "➕ Import Wallpaper";
            clicked => { root.import_wallpaper(); }
        }

        Rectangle {
            height: Theme.border-thin;
            border-radius: Theme.radius-small;
            background: Theme.divider;
        }

        SidebarButton {
            title: "❕ About";
            clicked => { root.show_about(); }
        }
    }
}
