import { VerticalBox } from "std-widgets.slint";
import { SidebarButton } from "sidebar-button.slint";

export component AppSidebar inherits Rectangle {
    background: #120f1a;
    width: 220px;
    border-radius: 8px;
    border-width: 1px;
    border-color: #2a2040;

    callback import_wallpaper();
    callback show_about();

    VerticalBox {
        padding: 10px;
        spacing: 10px;

        SidebarButton {
            title: "➕ Import Wallpaper";
            clicked => { root.import_wallpaper(); }
        }

        Rectangle {
            height: 1px;
            border-radius: 8px;
            background: #312648;
        }

        SidebarButton {
            title: "❕ About";
            clicked => { root.show_about(); }
        }
    }
}
